import { Transaction, Account } from '@/types';

// Mock accounts
export const MOCK_ACCOUNTS: Account[] = [
  {
    id: '1',
    user_id: 'user-1',
    name: 'Cash',
    type: 'cash',
    balance: 1250.0,
    currency: 'USD',
    color: '#10B981',
    icon: 'cash',
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    user_id: 'user-1',
    name: 'Main Bank',
    type: 'bank',
    balance: 14820.5,
    currency: 'USD',
    color: '#2563EB',
    icon: 'bank',
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    user_id: 'user-1',
    name: 'Jazz Cash',
    type: 'wallet',
    balance: 3200.0,
    currency: 'USD',
    color: '#8B5CF6',
    icon: 'wallet',
    created_at: new Date().toISOString(),
  },
];

// Mock recent transactions
export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: 't1',
    user_id: 'user-1',
    account_id: '2',
    category_id: 'food',
    amount: 45.0,
    type: 'expense',
    note: 'Dinner at restaurant',
    date: new Date(Date.now() - 1 * 86400000).toISOString(),
    created_at: new Date().toISOString(),
    category: {
      id: 'food',
      name: 'Food',
      icon: 'fast-food',
      color: '#F59E0B',
      type: 'expense',
    },
    account: MOCK_ACCOUNTS[1],
  },
  {
    id: 't2',
    user_id: 'user-1',
    account_id: '1',
    category_id: 'salary',
    amount: 5000.0,
    type: 'income',
    note: 'Monthly salary',
    date: new Date(Date.now() - 2 * 86400000).toISOString(),
    created_at: new Date().toISOString(),
    category: {
      id: 'salary',
      name: 'Salary',
      icon: 'briefcase',
      color: '#10B981',
      type: 'income',
    },
    account: MOCK_ACCOUNTS[0],
  },
  {
    id: 't3',
    user_id: 'user-1',
    account_id: '3',
    category_id: 'transport',
    amount: 12.0,
    type: 'expense',
    note: 'Uber ride',
    date: new Date(Date.now() - 3 * 86400000).toISOString(),
    created_at: new Date().toISOString(),
    category: {
      id: 'transport',
      name: 'Transport',
      icon: 'car',
      color: '#3B82F6',
      type: 'expense',
    },
    account: MOCK_ACCOUNTS[2],
  },
  {
    id: 't4',
    user_id: 'user-1',
    account_id: '2',
    category_id: 'shopping',
    amount: 89.99,
    type: 'expense',
    note: 'New shirt',
    date: new Date(Date.now() - 4 * 86400000).toISOString(),
    created_at: new Date().toISOString(),
    category: {
      id: 'shopping',
      name: 'Shopping',
      icon: 'bag',
      color: '#8B5CF6',
      type: 'expense',
    },
    account: MOCK_ACCOUNTS[1],
  },
  {
    id: 't5',
    user_id: 'user-1',
    account_id: '2',
    category_id: 'freelance',
    amount: 750.0,
    type: 'income',
    note: 'Freelance project',
    date: new Date(Date.now() - 5 * 86400000).toISOString(),
    created_at: new Date().toISOString(),
    category: {
      id: 'freelance',
      name: 'Freelance',
      icon: 'laptop',
      color: '#2563EB',
      type: 'income',
    },
    account: MOCK_ACCOUNTS[1],
  },
];
